version: '3.8'
services:
  backend:
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/emsp?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: emsp
    volumes:
      - ./db-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck: # 健康检查
      test: [ "CMD", "mysqladmin", "ping", "-uroot", "-p123456" ]
      interval: 5s
      timeout: 10s
      retries: 10
networks:
  app-network:
    driver: bridge