spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/emsp?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull}
logging:
  level:
    root: INFO
    org:
      springframework: INFO
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.edwin.emsp.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-argument: true
springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    path: /v3/api-docs
  cache:
    disabled: true